### ISSUE TITLE
mqKeyRepository configuration issue for ACE

### ISSUE THREAD

**Issue by Gopi78** [ot4i/ace-docker#34]
Hi,

We are trying to configure MQ SSL properties on the ACE MQOutput node. 

mqKeyRepository configuration needs to be configured under BrokerRegistry in server.conf.yaml file. We tried KDB and JKS keystores but only KDB is accepted. Also, the keystore file needs to be stashed.

Current scripts use the java keytool (/jre/bin/keytool) command but building kdb and password stash using keytool is not possible.

Could you please advise whether JKS is supported for mqKeyRepository ?

or any helm chart update possible with "runmqckm" tool?

Thanks for your help.

Regards,
Gopal

**Comment by IBMRob** [comment]
Hi @Gopi78,

Unfortunately we don't provide a mechanism for configuring MQ SSL on the MQ nodes. I have added this to our requirements backlog. I will keep this open to provide any updates.

What would you ideal support provide?
Support for taking a KDB and automatically configuring the integration server to use it?

**Comment by Gopi78** [comment]
Hi Rob,

Sorry for the late response.

I think the MQ nodes accept the SSL parameters. The below configuration in yaml will accept the mq key stores

BrokerRegistry:
   mqKeyRepository: 'E:\Repository\mq\ace\key'

my question was; there are no keytool installations in ACE to check the keystore certs to debug.

Thanks,
Gopal

**Comment by Gopi78** [comment]
Hi Rob,

Just to confirm. currently the integration server (ACE) will not have SSL for MQ Output nodes ?

we are trying to connect to remote queue manager using client connection properties.

Thanks,
Gopal

Thanks,
Gopal

**Comment by IBMRob** [comment]
@Gopi78 - By default while you can provide a server.config.yaml that specifies the mqKeyRepository we don't have a mechanism to create that file with the appropriate keys. If you built a new image using ours as a "FROM" then you could manually add that file and then configure the server.conf.yaml as you have described

**Comment by Gopi78** [comment]
Hi Rob,

Thanks for the update. mykeyrepository config is working fine from local windows ace server -> mq docker (ubuntu) image.

But the same is failing from ace image -> mq docker image.

I performed the below

1) implemented a script to copy the key.kdb and key.sth to /home/aceuser/ace-server 
2) copied the server.config.yaml to  /home/aceuser/ace-server/overrides which has mqkeyrpository and jvm jks stores.
3) jvm key stores are working fine for https conenctions
4) but ace is not picking the mqkeyrepository. I tested without ssl and mq configurations are working fine.

can you please advise whether anything I am missing or ace/mqclient image misses any libraries?

Thanks,
Gopal

**Comment by IBMRob** [comment]
Just to clarify you are using an image that has been built from the ace image + mqclient libraries installed?

There is nothing about running in a docker image that should affect it working. Provided you have make exactly the same configuration changes to the integration server running docker as to the integration server running on your laptop it should work. Docker it self does not restrict this in any way. I suspect its a configuration that has been missed within docker that has been set on your local installation. 

In your description you mention your copying the server.config.yaml directly into the overrides folder. Is this being done as another docker build step? Our image are designed for the server.conf.yaml to be stored as a secret and then loaded on startup. Its probably worth looking inside your running container and double checking that everything you expect is where it is with the correct contents

**Comment by Gopi78** [comment]
Hi Rob, 

Yes, we are using the docker image with mqclient libraries. Also, we are using secrets to copy the initial configuration and overides. 

As part of the image + secrets,  it copies the server.config.yaml to overrides folder. 

I have done the exact configurations similar to local machine. 

The only difference I can see is the gskit is not in the mqclient folder.  Could that cause an issue? 

Also, the runmqckm commands could not be issued in the docker. I could not find the installations.

Thanks for your help. 

Regards, 
Gopal

**Comment by IBMRob** [comment]
AH yes - gskit is needed to do SSL with MQ I think. If you update the MQ client install to also install that hopefully that should fix it

**Comment by Gopi78** [comment]
Thanks Rob. I will work on installing the gskit. Will update you.

Regards, 
Gopal

**Comment by Gopi78** [comment]
Hi Rob, 

Could you please provide me the latest gskit Linux software location. 

I copied the gskit8 from mq container to ace container (under /opt/mqm) but got an exception stating version 8.0.50.2 needs to be upgraded to 8.0.55.xx .

Tried to perform fix pack but did not work. 

If I can get the latest gskit then can copy the whole folder to the ace container. 

Thanks, 
Gopal

**Comment by IBMRob** [comment]
@Gopi78 

Please follow https://www.ibm.com/support/home/links/98/product/P439881V74305Y86/websphere/ibm_mq?results=8 for all MQ downloads

**Comment by Mukul1586** [comment]
Hi Rob,

we have a requirement of MQinput node making an SSL connection to the remote queue manager using  Client connection properties.

We are using independent  integration server as per  our design .
Even after the above mentioned steps, i am still getting the below error.

The integration node registry object parameter 'mqKeyRepository' is not set.

Would that be because  mqKeyRepository   can only be set at Integration node level by BrokerRegistry or mqsichangeproperties ? 
if yes? Is there any  way around we can have our requirement fulfilled ?
